Create Journal Editor Component
cse110-sp24-group35/journal pull request #18
Opened 2024-05-24 04:12 UTC by mbizzigotti

## Description

This PR creates the journal's editor component, including a markdown editor.

## Related Issue

Closes #5

## How Has This Been Tested?

TODO

## Checklist
- [ ] All automated tests have been passed locally (unit / e2e / linter / coverage)
- [ ] New unit and E2E tests have been added to address the changes made
- [ ] Manual testing has been performed according to the provided instructions
- [ ] Code follows team's coding style, convention and standards
- [ ] Documentation has been updated to reflect relevant changes (if applicable)

## Screenshots (if applicable):

2024-06-03 01:59 UTC, Ant044 commented on src/scripts/components/journal-editor.js
> +        return null;
Is this supposed to return null?

2024-06-03 03:59 UTC, jxnxthxnz commented on src/journal.html
>      <modal-journal></modal-journal>
just comment this out for now

2024-06-03 03:59 UTC, jxnxthxnz commented on src/journal.html
> -    <!-- Include the JavaScript file defining the Web Component -->
keep this, just comment it out for now

2024-06-03 05:34 UTC, jxnxthxnz commented on src/styles/journal-editor.css
> +}
are you able to put the css within the webcomponent in journal-editor.js?

2024-06-03 08:58 UTC, Ant044 commented on src/styles/journal-editor.css
> +form > * {
This also makes the text white, rendering everything invisible if not selected

![image](https://github.com/cse110-sp24-group35/journal/assets/146861585/059ffa16-6070-40e7-9081-9cfd6526ce5a)

2024-06-03 09:02 UTC, Ant044 commented on src/scripts/components/journal-editor.js
> +        //});
Did you mean to leave this section commented out?

2024-06-03 09:19 UTC, Ant044 commented
Not sure if you meant to leave a bunch of things commented, but after uncommenting and removing those and the form > * css style, it looked like this on my end: 
![image](https://github.com/cse110-sp24-group35/journal/assets/146861585/81920777-f91c-446b-9201-37d7f0ca6003)

One issue is that the buttons on the left seem to be all in a column instead of mostly a row. Clicking them doesn't seem to do anything because any selected text I was trying to bold gets unselected when I click the drop down to bold it.

2024-06-05 03:41 UTC, nadecancode requested changes

2024-06-05 03:41 UTC, nadecancode commented on src/scripts/components/journal-editor.js
> +		const style = document.createElement('style');
Indent probably doesn't pass linter, need to fix

2024-06-05 03:41 UTC, nadecancode commented on src/scripts/components/journal-editor.js
> +        this.path = "null";
use `undefined` or `null`, never set it to a stringified `null` because it can mean 2 things:
1. The journal file is `null` from the root directory
2. The journal does not have a path

2024-06-05 04:41 UTC, nadecancode commented
Looks good now

2024-06-05 04:41 UTC, merged