Jonathan/Create new journal CSS and HTML files
cse110-sp24-group35/journal pull request #19
Opened 2024-05-26 05:31 UTC by jxnxthxnz

## Description

Implemented the HTML and CSS for the modal that should appear for the create a new journal feature. 
## Related Issue

https://github.com/cse110-sp24-group35/journal/issues/6

## How Has This Been Tested?

Ran an e2e test in journal.test.js

## Checklist
- [x] All automated tests have been passed locally (unit / e2e / linter / coverage)
- [x] New unit and E2E tests have been added to address the changes made
- [x] Manual testing has been performed according to the provided instructions
- [x] Code follows team's coding style, convention and standards
- [x] Documentation has been updated to reflect relevant changes (if applicable)

## Screenshots (if applicable):

2024-05-26 05:41 UTC, nadecancode requested changes

2024-05-26 05:41 UTC, nadecancode commented on src/journal.html
> +    <button id="openModalBtn">Add New Flight</button> <!-- Button to open the modal -->
New Flight?

2024-05-26 05:41 UTC, nadecancode commented on src/journal.html
> +    <div class="modal">
I think you should use WebComponent to implement modal, this offers more granulated control and better scoping. Here is an example: https://github.com/Polydile/dile-components/blob/master/packages/dile-modal/src/DileModal.js

2024-05-26 05:41 UTC, nadecancode commented on src/styles/journal.css
> +body {
Don't add global styles for a modal component

2024-05-26 05:41 UTC, nadecancode commented on src/styles/journal.css
> +body {
These things should exist in a common CSS file that is shared by all pages.

2024-05-26 05:41 UTC, nadecancode commented on src/styles/journal.css
> +    font-family: Arial, sans-serif;
No need to add font here

2024-05-26 05:41 UTC, nadecancode commented on src/styles/journal.css
> +h2 {
Don't add global style

2024-05-26 05:41 UTC, nadecancode commented on src/styles/journal.css
> +form {
See above

2024-05-26 05:41 UTC, nadecancode commented on src/styles/journal.css
> +label {
^

2024-05-26 05:41 UTC, nadecancode commented on src/styles/journal.css
> +input[type="text"],
^

2024-05-26 05:41 UTC, nadecancode commented on src/journal.html
> +    <button id="openModalBtn">Add New Flight</button> <!-- Button to open the modal -->
Is the function to toggle modal appearance still yet to be implemented? I don't see anywhere that does modal rendering

2024-05-26 05:41 UTC, nadecancode commented on src/test/e2e/journal.test.js
> +            return style.display !== 'none';
The flow should be like this:
1. The display is none by default, since all modals are invisible without actions in user's end
2. Click the button
3. Check if modal shows up now
4. Click something to close modal
5. Check if modal disappears now

2024-05-27 09:19 UTC, jxnxthxnz commented on src/journal.html
> +    <button id="openModalBtn">Add New Flight</button> <!-- Button to open the modal -->
ivor and vincent are creating the function and button

2024-05-27 09:23 UTC, jxnxthxnz commented on src/test/e2e/journal.test.js
> +            return style.display !== 'none';
i think i may have to update this later when the ivor and vincent finish up their end of the code

2024-05-28 02:29 UTC, nadecancode requested changes

2024-05-28 02:29 UTC, nadecancode commented on src/scripts/modal-component.js
> +        super();
super() is implied and iirc you don't need one here

2024-05-28 02:29 UTC, nadecancode commented on src/scripts/modal-component.js
> +        style.textContent = `
I'm ***not sure*** if textContent will work for all browsers, I recommend to use innerHTML

2024-05-28 02:29 UTC, nadecancode commented on src/scripts/modal-component.js
> +customElements.define('modal-component', ModalComponent);
I think there will be a modal for create task as well, defining this as "modal-component" is probably confusing

2024-05-28 03:13 UTC, jxnxthxnz commented on src/scripts/modal-component.js
> +        super();
I tried it without the super() and it wouldn't work anymore. I think you do need it

2024-05-28 03:19 UTC, nadecancode approved these changes

2024-05-28 03:22 UTC, merged