Create New Journal Button
cse110-sp24-group35/journal pull request #28
Opened 2024-05-27 22:36 UTC by ivormyers

## Description
Wrote html and css for basic new journal button. 

## Related Issue
Issue 6 Journal | Create New Journal

https://github.com/cse110-sp24-group35/journal/issues/6

## How Has This Been Tested?

Tested visually through live server

## Checklist
- [ X] All automated tests have been passed locally (unit / e2e / linter / coverage)
- [ ] New unit and E2E tests have been added to address the changes made
- [X ] Manual testing has been performed according to the provided instructions
- [ x] Code follows team's coding style, convention and standards
- [ ] Documentation has been updated to reflect relevant changes (if applicable)

## Screenshots (if applicable):

2024-05-28 02:31 UTC, nadecancode requested changes

2024-05-28 02:31 UTC, nadecancode commented on src/styles/main.css
> +.newjournalbutton {
use dashed naming e.g. new-journal-button

2024-05-28 02:31 UTC, nadecancode commented on src/styles/main.css
> +      padding: 10px 20px;            /* Padding */
Use relative unit

2024-05-28 04:49 UTC, jxnxthxnz commented on src/journal.html
> +    <button class = "newjournalbutton">+</button>
Use "Add a new journal" rather than "+"

2024-05-29 21:13 UTC, ivormyers reviewed
Updated pull request to meet comments added

2024-06-05 00:48 UTC, jxnxthxnz commented on src/journal.html
> +    <button class = "newjournalbutton">+</button>
make this a webcomponent and put the file under the new components folder. add all the css and js stuff in that web component. ensure when you click your button, it will call my modal.

2024-06-05 21:33 UTC, ivormyers reviewed
button is now working to make modal appear - next step is to ensure it saves properly

2024-06-05 22:17 UTC, nadecancode approved these changes

2024-06-05 22:18 UTC, merged