Started working on local storage with creating journal
cse110-sp24-group35/journal pull request #29
Opened 2024-05-29 23:00 UTC by VinMoeMac

## Description

Added a main js with form handler and other functions dealing with getting from storage and adding to storage
## Related Issue

## How Has This Been Tested?

untested pretty much still in early stages
## Checklist
- [ ] All automated tests have been passed locally (unit / e2e / linter / coverage)
- [ ] New unit and E2E tests have been added to address the changes made
- [ ] Manual testing has been performed according to the provided instructions
- [ ] Code follows team's coding style, convention and standards
- [ ] Documentation has been updated to reflect relevant changes (if applicable)

## Screenshots (if applicable):

2024-06-05 01:07 UTC, jxnxthxnz commented on src/styles/main.css
> +}
move this into the modal-journal.js

2024-06-05 01:09 UTC, nadecancode requested changes

2024-06-05 01:09 UTC, nadecancode commented on src/scripts/database/stores/journal.js
> +        dueDate,
A journal should not have due date, it's task's property isn't it?

2024-06-05 01:09 UTC, nadecancode commented on src/scripts/modal-journal.js
> +            due: formData.get('due'),
I don't think we need due date when creating a journal

2024-06-05 01:09 UTC, nadecancode commented on src/scripts/modal-journal.js
> +            due: formData.get('due'),
Instead, we ask user to link tasks when creating a journal

2024-06-05 01:09 UTC, nadecancode commented on src/scripts/modal-journal.js
> +        createJournal(formData.get('title'),formData.get('path'),formData.get('tags'),formData.get('due'));
^

2024-06-07 21:23 UTC, nadecancode approved these changes

2024-06-07 21:23 UTC, nadecancode commented on src/scripts/modal-journal.js
> +        console.log('Journal created: ', getJournal(formData.get('path')));
Should be removed in production but I guess it's ok for now

2024-06-07 21:29 UTC, merged